### ISSUE TITLE
Create Compendium client for Scala

### ISSUE THREAD

**Issue by rafaparadela** [higherkindness/sbt-compendium#2]
We should create a Compendium HTTP client in Scala that will be used inside the sbt-compendium plugin.

This http client would need to interact with the code generation endpoint in Compendium server.

Ideally, we would bootstrap this. (Making sbt-compendium depend on sbt-compendium to allow Compendium to create the Compendium client :D)

**Comment by pepegar** [comment]
This issue was done in https://github.com/higherkindness/compendium/pull/48
